### ISSUE TITLE
брад

### ISSUE THREAD

**Issue by rldv1** [kararasenok-gd/JRAT_Ru#1]
что это за кринж братик 
![image](https://user-images.githubusercontent.com/118821863/224724229-471b494c-45d7-4d7c-a760-02b559efa170.png)

**Comment by tailsjs** [comment]
конкурс на бонуски
![image](https://user-images.githubusercontent.com/49571184/224724377-d1587b81-38af-4094-ad8a-a6468ca395f3.png)

**Comment by SavokBS** [comment]
Дебил тупой у тебя нет аргументов кроме родителей бездарь иди делай уроки лучше даунище ебаное почему ты осеорбляешь моих друзей дебил я тебе запрещаю это делать дебил ты ваще умственно отсталый дебил почему ты моих друзей осокрьлять дебил тупой закрой свою пасть лучше и иди делай уроки а лучше полностью изолируйс что интернета тварь тупая рот будешь открывать у стаматолага

**Comment by rldv1** [comment]
осеорбляешь

**Comment by rldv1** [comment]
осеорбляею и буду осеорблять

**Comment by tailsjs** [comment]
не оскорбляй пж...

**Comment by rldv1** [comment]
![image](https://user-images.githubusercontent.com/118821863/224729833-aaa18251-c82f-4d2d-b4f0-28fb5bbddc69.png)
